[project]
name = "shepherdx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiomqtt>=2.4.0",
    "asyncio>=4.0.0",
    "fastapi>=0.124.4",
    "typing>=3.10.0.0",
    "uvicorn>=0.38.0",
]
